# Configuration Prometheus pour Portfolio RL
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'portfolio-rl-monitor'

# Règles d'alertes
rule_files:
  - "alert_rules.yml"

# Configuration des alertes
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Jobs de collecte de métriques
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # API Portfolio RL
  - job_name: 'portfolio-api'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 10s
    honor_labels: true

  # API FastAPI principale (si métriques intégrées)
  - job_name: 'portfolio-fastapi'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node Exporter (métriques système)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # MLflow (si métriques disponibles)
  - job_name: 'mlflow'
    static_configs:
      - targets: ['localhost:5001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Blackbox Exporter pour tests de connectivité
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://localhost:8000/health
        - http://localhost:5000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

# Configuration de stockage
storage:
  tsdb:
    path: /prometheus
    retention:
      time: 30d
      size: 10GB

# Configuration web
web:
  console:
    libraries: /etc/prometheus/console_libraries
    templates: /etc/prometheus/consoles
  enable_lifecycle: true
  enable_admin_api: true